[window]
opacity = 0.85
startup_mode = "Windowed"
blur = true
padding = { x = 3, y = 3 }
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 5

[font]
# linux
# normal = {family = "SauceCodePro NFM", style = "Regular"}

# macos
normal = { family = "SauceCodePro Nerd Font", style = "Medium" }

size = 15
