[window]
opacity = 0.85
startup_mode = "Windowed"
blur = true
padding = {x=3, y=3}

[scrolling]
history = 50000
multiplier= 5

[font]
# normal = {family = "ComicShannsMono Nerd Font", style = "Regular"}
normal = {family = "SauceCodePro NFM", style = "Regular"}

